name: Docker Publish

on:
  push:     
    # tags: [ 'v*.*.*' ]
    branch: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login Registry
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: |
            zcx2001/java8builder:latest


#            zcx2001/java8builder:${{ github.ref_name }} 